version: "3.8"

services:
  binance-market-monitor:
    image: crazygit/binance-market-monitor:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_CHANNEL_USERNAME: ${TELEGRAM_CHANNEL_USERNAME}
      QUOTE_ASSET: ${QUOTE_ASSET}
      LOWEST_PRICE_FILTER: ${LOWEST_PRICE_FILTER}
      PRICE_CHANGE_PERCENT_THRESHOLD: ${PRICE_CHANGE_PERCENT_THRESHOLD}
      PRICE_CHANGE_THRESHOLD: ${PRICE_CHANGE_THRESHOLD}
      CLOSE_QTY_THRESHOLD: ${CLOSE_QTY_THRESHOLD}
