version: "3.8"

services:
  binance-market-monitor:
    image: crazygit/binance-market-monitor:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_CHANNEL_USERNAME: ${TELEGRAM_CHANNEL_USERNAME}
      QUOTE_ASSET: ${QUOTE_ASSET}
